### ISSUE TITLE
Bash script doesn't work as intended when a user enters a space, single quote, or double quote character

### ISSUE THREAD

**Issue by matthamil** [matthamil/Bash-Scripts#1]
In [githubRepoMaker.sh](https://github.com/matthamil/Bash-Scripts/blob/master/githubRepoMaker.sh), if a user enters a space, single quote, or double quote when the script prompts the user for a repository name, the script does not properly create a new repo with the name entered. Some kind of safety feature needs to be implemented to allow users to enter spaces, single quotes, or double quotes in a repository name.

**Comment by iordic** [comment]
I can try to help you if u want.

**Comment by ricciocri** [comment]
Please check my PR, this should solve your problem.
